//! `control_plane_certificates` — the TLS certificate the control plane serves
//! the dashboard with. Exactly one row is active; a row keeps its private key in
//! plain text so a certificate can be swapped without an operator on the box.

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// `control_plane_certificates` — one served certificate per row.
pub mod control_plane_certificates {
    use super::*;

    #[derive(
        Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize,
    )]
    #[sea_orm(table_name = "control_plane_certificates")]
    pub struct Model {
        #[sea_orm(primary_key, auto_increment = false)]
        pub id: Uuid,
        /// `self_signed` (generated by the control plane) or `uploaded`.
        pub source: String,
        /// PEM chain: leaf first, then any intermediates.
        #[sea_orm(column_type = "Text")]
        pub cert_pem: String,
        #[sea_orm(column_type = "Text")]
        pub key_pem: String,
        pub subject_dn: String,
        pub common_name: Option<String>,
        /// Subject alternative names, as a JSON array of strings.
        #[sea_orm(column_type = "JsonBinary")]
        pub sans: Json,
        pub serial: String,
        pub fingerprint_sha256: String,
        pub not_before: DateTimeUtc,
        pub not_after: DateTimeUtc,
        pub is_active: bool,
        pub created_by: Option<Uuid>,
        pub created_at: DateTimeUtc,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}

    impl ActiveModelBehavior for ActiveModel {}
}

/// Where a certificate came from.
pub mod source {
    /// Generated by the control plane when nothing was uploaded yet.
    pub const SELF_SIGNED: &str = "self_signed";
    /// Uploaded by an administrator.
    pub const UPLOADED: &str = "uploaded";
}
