pub mod cache;
pub mod cert_events;
pub mod cert_status;
pub mod client;
pub mod config;
pub mod heartbeat;
pub mod probe;

use std::sync::Arc;

use arc_swap::ArcSwapOption;
use tracing::{error, info};

use cache::RuleCache;
use client::ControlPlaneClient;
use config::AgentConfig;
use heartbeat::MetricsCollector;

// ─────────────────────────────────────────────────────────────
// Global agent instance (singleton)
// ─────────────────────────────────────────────────────────────

static AGENT_INSTANCE: ArcSwapOption<PingWafAgent> =
    ArcSwapOption::const_empty();

// ─────────────────────────────────────────────────────────────
// Simplified types for the plugin API
// (don't expose proto types to consumers)
// ─────────────────────────────────────────────────────────────

/// A security event generated by the WAF engine.
///
/// Sent to the control plane for analysis and dashboard display.
#[derive(Debug, Clone)]
pub struct SecurityEvent {
    pub site_id: String,
    pub request_id: String,
    pub client_ip: String,
    pub method: String,
    pub scheme: String,
    pub protocol: String,
    pub host: String,
    pub path: String,
    pub query_string: String,
    pub rule_id: String,
    pub rule_name: String,
    /// Which protection produced the event: `managed` / `waf` / `ip_geo` /
    /// `bot` / `rate_limit` / `challenge`. Drives dashboard deep links.
    pub event_type: String,
    pub action: String,
    pub score: u32,
    pub details: String,
    /// Status code actually returned to the client for this event
    /// (403 for block, 503 for challenge, 0 when the request continues).
    pub response_status: u32,
    pub user_agent: String,
    pub country_code: String,
    pub matched_tags: Vec<String>,
}

/// An access log entry for a proxied request.
///
/// Batched and shipped to the control plane for analytics.
#[derive(Debug, Clone)]
pub struct AccessLogEntry {
    pub site_id: String,
    pub request_id: String,
    pub client_ip: String,
    pub method: String,
    pub scheme: String,
    pub host: String,
    pub path: String,
    pub query_string: String,
    pub protocol: String,
    pub status_code: u32,
    pub response_size: u64,
    pub upstream_addr: String,
    pub upstream_latency_ms: u64,
    pub total_latency_ms: u64,
    pub cache_status: String,
    pub user_agent: String,
    pub referer: String,
    pub tls_version: String,
    pub country_code: String,
    pub request_headers: Vec<(String, String)>,
    pub request_body: Option<Vec<u8>>,
    pub request_body_size: u64,
    pub request_body_truncated: bool,
    /// Response header snapshot, capped like the request one.
    pub response_headers: Vec<(String, String)>,
    /// Prefix of the response body kept for the log; `None` when it was not
    /// captured (binary payload, compressed, or capture disabled).
    pub response_body: Option<Vec<u8>>,
    /// Full response body size as counted while streaming, kept or not.
    pub response_body_size: u64,
    pub response_body_truncated: bool,
}

// ─────────────────────────────────────────────────────────────
// PingWafAgent — the main public interface
// ─────────────────────────────────────────────────────────────

/// The PingWAF agent that connects to the control plane, caches rules locally,
/// and provides an API for pingap plugins to query WAF state.
///
/// # Usage
///
/// ```no_run
/// use pingwaf_agent::{PingWafAgent, config::AgentConfig};
///
/// # async fn example() -> anyhow::Result<()> {
/// // Start the agent (connects to control plane in background)
/// let agent = PingWafAgent::start(AgentConfig::default()).await?;
///
/// // Query rules for a domain
/// if let Some(rules) = agent.get_rules_for_domain("example.com") {
///     println!("WAF enabled: {:?}", rules.waf_config);
/// }
/// # Ok(())
/// # }
/// ```
pub struct PingWafAgent {
    pub config: AgentConfig,
    pub client: Arc<ControlPlaneClient>,
    pub rule_cache: Arc<RuleCache>,
    pub metrics: Arc<MetricsCollector>,
}

impl PingWafAgent {
    /// Initialize and start the agent.
    ///
    /// This connects to the control plane server in the background,
    /// registers the agent, and starts heartbeat/log-shipping tasks.
    /// If the server is unreachable, the agent operates from cached rules.
    pub async fn start(config: AgentConfig) -> anyhow::Result<Arc<Self>> {
        info!("Starting PingWAF agent...");

        let agent_id = config.resolved_agent_id();
        let cache_dir = std::path::PathBuf::from(&config.cache_dir);

        // Initialize rule cache (loads from disk if available)
        let rule_cache = RuleCache::new(cache_dir, agent_id.clone())?;

        // Initialize metrics collector
        let metrics = Arc::new(MetricsCollector::new());

        // Create the gRPC client
        let client = Arc::new(ControlPlaneClient::new(
            config.clone(),
            Arc::clone(&rule_cache),
            Arc::clone(&metrics),
        ));

        let agent = Arc::new(Self {
            config,
            client: Arc::clone(&client),
            rule_cache,
            metrics,
        });

        // Set as global instance
        AGENT_INSTANCE.store(Some(Arc::clone(&agent)));

        // Start background tasks (connection, heartbeat, log shipping)
        if let Err(e) = client.start().await {
            error!(error = %e, "Failed to start client background tasks");
            // Don't fail — agent can still operate from cached rules
        }

        info!(agent_id = %agent_id, "PingWAF agent started");
        Ok(agent)
    }

    /// Get the global agent instance (if started).
    pub fn instance() -> Option<Arc<Self>> {
        AGENT_INSTANCE.load_full()
    }

    /// Replace the global agent instance. Only compiled with the
    /// `test-util` feature: lets integration tests install an agent built
    /// without connecting to a control plane.
    #[cfg(feature = "test-util")]
    pub fn set_agent_instance(agent: Option<Arc<Self>>) {
        AGENT_INSTANCE.store(agent);
    }

    /// Get rules for a specific domain (used by WAF plugin on the hot path).
    ///
    /// Returns `None` if no rules are cached for this domain.
    #[inline]
    pub fn get_rules_for_domain(
        &self,
        domain: &str,
    ) -> Option<Arc<cache::SiteRules>> {
        self.rule_cache.get_site_rules(domain)
    }

    /// Get rules for a specific site by ID.
    #[inline]
    pub fn get_rules_for_site(
        &self,
        site_id: &str,
    ) -> Option<Arc<cache::SiteRules>> {
        self.rule_cache.get_site_rules_by_id(site_id)
    }

    /// Check if an IP is dynamically blocked for a site.
    #[inline]
    pub fn is_ip_blocked(&self, site_id: &str, ip: &str) -> bool {
        self.rule_cache.is_ip_blocked(site_id, ip)
    }

    /// Dynamically block an IP for a site. Called by the WAF plugin when a
    /// block verdict fires so the edge keeps refusing the client before the
    /// engine even runs; the block is reported to the control plane on the
    /// next heartbeat.
    #[inline]
    pub fn block_ip(
        &self,
        site_id: &str,
        ip: &str,
        duration: Option<std::time::Duration>,
        reason: &str,
    ) {
        self.rule_cache.block_ip(site_id, ip, duration, reason)
    }

    /// Log a security event (non-blocking, queued for batch shipping).
    pub fn log_security_event(&self, event: SecurityEvent) {
        let entry = client::LogEntry {
            site_id: event.site_id,
            request_id: event.request_id,
            client_ip: event.client_ip,
            method: event.method,
            scheme: event.scheme,
            host: event.host,
            path: event.path,
            query_string: event.query_string,
            protocol: event.protocol,
            request_headers: std::collections::HashMap::new(),
            request_body: None,
            request_body_size: 0,
            request_body_truncated: false,
            response_status: event.response_status,
            response_headers: std::collections::HashMap::new(),
            response_body: None,
            response_body_size: 0,
            response_body_truncated: false,
            upstream_addr: String::new(),
            upstream_latency_ms: 0,
            waf_score: event.score,
            waf_action: event.action,
            waf_rule_id: event.rule_id,
            waf_rule_name: event.rule_name,
            waf_event_type: event.event_type,
            waf_details: event.details,
            waf_matched_tags: event.matched_tags,
            total_latency_ms: 0,
            cache_status: String::new(),
            tls_version: String::new(),
            ja3_hash: String::new(),
            country_code: event.country_code,
            city: String::new(),
            asn: 0,
            user_agent: event.user_agent,
            referer: String::new(),
        };
        self.client.send_log(entry);
    }

    /// Log an access entry (non-blocking, queued for batch shipping).
    pub fn log_access(&self, entry: AccessLogEntry) {
        let request_headers = combine_headers(entry.request_headers);
        let response_headers = combine_headers(entry.response_headers);
        let log_entry = client::LogEntry {
            site_id: entry.site_id,
            request_id: entry.request_id,
            client_ip: entry.client_ip,
            method: entry.method,
            scheme: entry.scheme,
            host: entry.host,
            path: entry.path,
            query_string: entry.query_string,
            protocol: entry.protocol,
            request_headers,
            request_body: entry.request_body,
            request_body_size: entry.request_body_size,
            request_body_truncated: entry.request_body_truncated,
            response_status: entry.status_code,
            response_headers,
            response_body: entry.response_body,
            response_body_size: entry.response_body_size,
            response_body_truncated: entry.response_body_truncated,
            upstream_addr: entry.upstream_addr,
            upstream_latency_ms: entry.upstream_latency_ms,
            waf_score: 0,
            waf_action: String::new(),
            waf_rule_id: String::new(),
            waf_rule_name: String::new(),
            waf_event_type: String::new(),
            waf_details: String::new(),
            waf_matched_tags: Vec::new(),
            total_latency_ms: entry.total_latency_ms,
            cache_status: entry.cache_status,
            tls_version: entry.tls_version,
            ja3_hash: String::new(),
            country_code: entry.country_code,
            city: String::new(),
            asn: 0,
            user_agent: entry.user_agent,
            referer: entry.referer,
        };
        self.client.send_log(log_entry);
    }

    /// Record a request for metrics (hot path — must be fast).
    #[inline]
    pub fn record_request(&self, blocked: bool) {
        self.metrics.record_request(blocked);
    }

    /// Record a connection change (+1 on accept, -1 on close).
    #[inline]
    pub fn record_connection(&self, delta: i64) {
        self.metrics.record_connection(delta);
    }

    /// Check if the agent is connected to the control plane.
    #[inline]
    pub fn is_connected(&self) -> bool {
        self.client.is_connected()
    }

    /// Whether `domain` should keep being served while the control plane is
    /// unreachable and no synced rules exist for it.
    ///
    /// Resolution order: the site's own failover policy from the registry
    /// (primary or alternate domain match), then the control-plane-wide
    /// default from the last sync, then this agent's local `--fail-open`
    /// setting — which is the only layer available in standalone mode or
    /// before the first sync completes.
    pub fn effective_fail_open(&self, domain: &str) -> bool {
        match self.rule_cache.failover_for_domain(domain) {
            Some(cache::FailoverMode::Open) => return true,
            Some(cache::FailoverMode::Closed) => return false,
            Some(cache::FailoverMode::Inherit) | None => {},
        }
        self.rule_cache
            .global_fail_open()
            .unwrap_or(self.config.fail_open)
    }

    /// Get the current config hash (for delta sync). Cheap: clones the `Arc`,
    /// not the string.
    pub fn config_hash(&self) -> Arc<str> {
        self.rule_cache.config_hash()
    }

    /// Graceful shutdown — signals all background tasks to stop.
    pub async fn shutdown(&self) {
        info!("Shutting down PingWAF agent...");
        self.client.shutdown();

        // Persist cache one final time
        if let Err(e) = self.rule_cache.persist_to_disk() {
            error!(error = %e, "Failed to persist cache during shutdown");
        }

        // Clear global instance
        AGENT_INSTANCE.store(None);
        info!("PingWAF agent shut down complete");
    }
}

/// Combines repeated header names into the single value the wire format's
/// header map accepts.
///
/// `Set-Cookie` pairs are joined with a newline instead of the canonical
/// comma: cookie values routinely carry `Expires`/`Path` attributes that
/// contain commas of their own, so a comma join makes the pairs
/// indistinguishable (`a=1, b=2` reads as one cookie or two depending on
/// the attribute). Consumers split this header on `\n` and the rest on `, `.
fn combine_headers(
    headers: Vec<(String, String)>,
) -> std::collections::HashMap<String, String> {
    let mut map: std::collections::HashMap<String, String> =
        std::collections::HashMap::with_capacity(headers.len());
    for (name, value) in headers {
        match map.entry(name) {
            std::collections::hash_map::Entry::Occupied(mut existing) => {
                let separator =
                    if existing.key().eq_ignore_ascii_case("set-cookie") {
                        "\n"
                    } else {
                        ", "
                    };
                let combined = existing.get_mut();
                combined.reserve(value.len() + separator.len());
                combined.push_str(separator);
                combined.push_str(&value);
            },
            std::collections::hash_map::Entry::Vacant(slot) => {
                slot.insert(value);
            },
        }
    }
    map
}

/// Start the PingWAF agent with the given configuration.
///
/// Convenience function that calls [`PingWafAgent::start`].
pub async fn start_agent(
    config: AgentConfig,
) -> anyhow::Result<Arc<PingWafAgent>> {
    PingWafAgent::start(config).await
}

/// Get the global agent instance (shorthand for [`PingWafAgent::instance`]).
pub fn agent_instance() -> Option<Arc<PingWafAgent>> {
    PingWafAgent::instance()
}

#[cfg(test)]
mod tests {
    use super::combine_headers;
    use super::*;
    use pingwaf_proto::control_plane as proto;

    /// Builds an offline agent whose cache carries the given failover
    /// registry and global default.
    fn agent_with(
        dir: &std::path::Path,
        local_fail_open: bool,
        policies: Vec<proto::SitePolicy>,
        global: Option<bool>,
    ) -> PingWafAgent {
        let mut config = AgentConfig::default();
        config.fail_open = local_fail_open;
        let rule_cache =
            RuleCache::new(dir.to_path_buf(), "test".to_string()).unwrap();
        let metrics = Arc::new(MetricsCollector::new());
        let client = Arc::new(ControlPlaneClient::new(
            config.clone(),
            Arc::clone(&rule_cache),
            Arc::clone(&metrics),
        ));
        rule_cache
            .update_from_bundle(&proto::RuleBundle {
                site_id: "site-1".to_string(),
                site_policies: policies,
                default_fail_open: global,
                ..Default::default()
            })
            .unwrap();
        PingWafAgent {
            config,
            client,
            rule_cache,
            metrics,
        }
    }

    #[test]
    fn failover_resolution_prefers_site_then_global_then_local() {
        let policy =
            |domain: &str, mode: proto::FailoverMode| proto::SitePolicy {
                domain: domain.to_string(),
                alternate_domains: Vec::new(),
                mode: mode as i32,
            };

        // Site policy wins over everything, in both directions. Every case
        // gets its own cache dir: the cache persists to disk, so sharing a
        // directory would leak one case's synced default into the next.
        let dir = tempfile::tempdir().unwrap();
        let agent = agent_with(
            dir.path(),
            true,
            vec![
                policy(
                    "closed.example.com",
                    proto::FailoverMode::FailoverClosed,
                ),
                policy("open.example.com", proto::FailoverMode::FailoverOpen),
            ],
            Some(true),
        );
        assert!(!agent.effective_fail_open("closed.example.com"));
        assert!(agent.effective_fail_open("open.example.com"));

        // Alternate domains resolve to the same policy.
        let dir = tempfile::tempdir().unwrap();
        let agent = agent_with(
            dir.path(),
            false,
            vec![proto::SitePolicy {
                domain: "example.com".to_string(),
                alternate_domains: vec!["m.example.com".to_string()],
                mode: proto::FailoverMode::FailoverOpen as i32,
            }],
            Some(false),
        );
        assert!(agent.effective_fail_open("m.example.com"));

        // Unknown domain: the synced global default applies, beating the
        // local setting.
        let dir = tempfile::tempdir().unwrap();
        let agent = agent_with(dir.path(), true, Vec::new(), Some(false));
        assert!(!agent.effective_fail_open("unknown.example.com"));

        // No synced global default (old control plane): the local fallback
        // decides.
        let dir = tempfile::tempdir().unwrap();
        let agent = agent_with(dir.path(), false, Vec::new(), None);
        assert!(!agent.effective_fail_open("unknown.example.com"));
        let dir = tempfile::tempdir().unwrap();
        let agent = agent_with(dir.path(), true, Vec::new(), None);
        assert!(agent.effective_fail_open("unknown.example.com"));
    }

    #[test]
    fn repeated_headers_join_with_a_comma() {
        let combined = combine_headers(vec![
            ("accept".to_string(), "text/html".to_string()),
            ("accept".to_string(), "application/json".to_string()),
        ]);
        assert_eq!(
            combined.get("accept").unwrap(),
            "text/html, application/json"
        );
    }

    #[test]
    fn set_cookie_pairs_stay_separated_by_newlines() {
        let combined = combine_headers(vec![
            ("set-cookie".to_string(), "a=1; Path=/".to_string()),
            (
                "set-cookie".to_string(),
                "b=2; Expires=Wed, 21 Oct 2026 07:28:00 GMT".to_string(),
            ),
        ]);
        // A comma join would make `b=2; Expires=Wed` and `21 Oct …` look like
        // separate cookies; the newline keeps every pair recoverable.
        assert_eq!(
            combined.get("set-cookie").unwrap(),
            "a=1; Path=/\nb=2; Expires=Wed, 21 Oct 2026 07:28:00 GMT"
        );
    }
}
