pub mod cache;
pub mod client;
pub mod config;
pub mod heartbeat;

use std::sync::Arc;

use arc_swap::ArcSwapOption;
use tracing::{error, info};

use cache::RuleCache;
use client::ControlPlaneClient;
use config::AgentConfig;
use heartbeat::MetricsCollector;

// ─────────────────────────────────────────────────────────────
// Global agent instance (singleton)
// ─────────────────────────────────────────────────────────────

static AGENT_INSTANCE: ArcSwapOption<PingWafAgent> = ArcSwapOption::const_empty();

// ─────────────────────────────────────────────────────────────
// Simplified types for the plugin API
// (don't expose proto types to consumers)
// ─────────────────────────────────────────────────────────────

/// A security event generated by the WAF engine.
///
/// Sent to the control plane for analysis and dashboard display.
#[derive(Debug, Clone)]
pub struct SecurityEvent {
    pub site_id: String,
    pub request_id: String,
    pub client_ip: String,
    pub method: String,
    pub host: String,
    pub path: String,
    pub query_string: String,
    pub rule_id: String,
    pub rule_name: String,
    pub action: String,
    pub score: u32,
    pub details: String,
    pub user_agent: String,
    pub country_code: String,
    pub matched_tags: Vec<String>,
}

/// An access log entry for a proxied request.
///
/// Batched and shipped to the control plane for analytics.
#[derive(Debug, Clone)]
pub struct AccessLogEntry {
    pub site_id: String,
    pub request_id: String,
    pub client_ip: String,
    pub method: String,
    pub scheme: String,
    pub host: String,
    pub path: String,
    pub query_string: String,
    pub protocol: String,
    pub status_code: u32,
    pub response_size: u64,
    pub upstream_addr: String,
    pub upstream_latency_ms: u64,
    pub total_latency_ms: u64,
    pub cache_status: String,
    pub user_agent: String,
    pub referer: String,
    pub tls_version: String,
    pub country_code: String,
    pub request_body: Option<Vec<u8>>,
    pub request_body_truncated: bool,
}

// ─────────────────────────────────────────────────────────────
// PingWafAgent — the main public interface
// ─────────────────────────────────────────────────────────────

/// The PingWAF agent that connects to the control plane, caches rules locally,
/// and provides an API for pingap plugins to query WAF state.
///
/// # Usage
///
/// ```no_run
/// use pingwaf_agent::{PingWafAgent, config::AgentConfig};
///
/// # async fn example() -> anyhow::Result<()> {
/// // Start the agent (connects to control plane in background)
/// let agent = PingWafAgent::start(AgentConfig::default()).await?;
///
/// // Query rules for a domain
/// if let Some(rules) = agent.get_rules_for_domain("example.com") {
///     println!("WAF enabled: {:?}", rules.waf_config);
/// }
/// # Ok(())
/// # }
/// ```
pub struct PingWafAgent {
    pub config: AgentConfig,
    pub client: Arc<ControlPlaneClient>,
    pub rule_cache: Arc<RuleCache>,
    pub metrics: Arc<MetricsCollector>,
}

impl PingWafAgent {
    /// Initialize and start the agent.
    ///
    /// This connects to the control plane server in the background,
    /// registers the agent, and starts heartbeat/log-shipping tasks.
    /// If the server is unreachable, the agent operates from cached rules.
    pub async fn start(config: AgentConfig) -> anyhow::Result<Arc<Self>> {
        info!("Starting PingWAF agent...");

        let agent_id = config.resolved_agent_id();
        let cache_dir = std::path::PathBuf::from(&config.cache_dir);

        // Initialize rule cache (loads from disk if available)
        let rule_cache = RuleCache::new(cache_dir, agent_id.clone())?;

        // Initialize metrics collector
        let metrics = Arc::new(MetricsCollector::new());

        // Create the gRPC client
        let client = Arc::new(ControlPlaneClient::new(
            config.clone(),
            Arc::clone(&rule_cache),
            Arc::clone(&metrics),
        ));

        let agent = Arc::new(Self {
            config,
            client: Arc::clone(&client),
            rule_cache,
            metrics,
        });

        // Set as global instance
        AGENT_INSTANCE.store(Some(Arc::clone(&agent)));

        // Start background tasks (connection, heartbeat, log shipping)
        if let Err(e) = client.start().await {
            error!(error = %e, "Failed to start client background tasks");
            // Don't fail — agent can still operate from cached rules
        }

        info!(agent_id = %agent_id, "PingWAF agent started");
        Ok(agent)
    }

    /// Get the global agent instance (if started).
    pub fn instance() -> Option<Arc<Self>> {
        AGENT_INSTANCE.load_full()
    }

    /// Get rules for a specific domain (used by WAF plugin on the hot path).
    ///
    /// Returns `None` if no rules are cached for this domain.
    #[inline]
    pub fn get_rules_for_domain(&self, domain: &str) -> Option<Arc<cache::SiteRules>> {
        self.rule_cache.get_site_rules(domain)
    }

    /// Get rules for a specific site by ID.
    #[inline]
    pub fn get_rules_for_site(&self, site_id: &str) -> Option<Arc<cache::SiteRules>> {
        self.rule_cache.get_site_rules_by_id(site_id)
    }

    /// Check if an IP is dynamically blocked for a site.
    #[inline]
    pub fn is_ip_blocked(&self, site_id: &str, ip: &str) -> bool {
        self.rule_cache.is_ip_blocked(site_id, ip)
    }

    /// Log a security event (non-blocking, queued for batch shipping).
    pub fn log_security_event(&self, event: SecurityEvent) {
        let entry = client::LogEntry {
            site_id: event.site_id,
            request_id: event.request_id,
            client_ip: event.client_ip,
            method: event.method,
            scheme: "https".to_string(),
            host: event.host,
            path: event.path,
            query_string: event.query_string,
            protocol: "HTTP/1.1".to_string(),
            request_headers: std::collections::HashMap::new(),
            request_body: None,
            request_body_size: 0,
            request_body_truncated: false,
            response_status: 403,
            response_headers: std::collections::HashMap::new(),
            upstream_addr: String::new(),
            upstream_latency_ms: 0,
            waf_score: event.score,
            waf_action: event.action,
            waf_rule_id: event.rule_id,
            waf_details: event.details,
            waf_matched_tags: event.matched_tags,
            total_latency_ms: 0,
            cache_status: String::new(),
            tls_version: String::new(),
            ja3_hash: String::new(),
            country_code: event.country_code,
            city: String::new(),
            asn: 0,
            user_agent: event.user_agent,
            referer: String::new(),
        };
        self.client.send_log(entry);
    }

    /// Log an access entry (non-blocking, queued for batch shipping).
    pub fn log_access(&self, entry: AccessLogEntry) {
        let log_entry = client::LogEntry {
            site_id: entry.site_id,
            request_id: entry.request_id,
            client_ip: entry.client_ip,
            method: entry.method,
            scheme: entry.scheme,
            host: entry.host,
            path: entry.path,
            query_string: entry.query_string,
            protocol: entry.protocol,
            request_headers: std::collections::HashMap::new(),
            request_body: entry.request_body,
            request_body_size: entry.response_size,
            request_body_truncated: entry.request_body_truncated,
            response_status: entry.status_code,
            response_headers: std::collections::HashMap::new(),
            upstream_addr: entry.upstream_addr,
            upstream_latency_ms: entry.upstream_latency_ms,
            waf_score: 0,
            waf_action: String::new(),
            waf_rule_id: String::new(),
            waf_details: String::new(),
            waf_matched_tags: Vec::new(),
            total_latency_ms: entry.total_latency_ms,
            cache_status: entry.cache_status,
            tls_version: entry.tls_version,
            ja3_hash: String::new(),
            country_code: entry.country_code,
            city: String::new(),
            asn: 0,
            user_agent: entry.user_agent,
            referer: entry.referer,
        };
        self.client.send_log(log_entry);
    }

    /// Record a request for metrics (hot path — must be fast).
    #[inline]
    pub fn record_request(&self, blocked: bool) {
        self.metrics.record_request(blocked);
    }

    /// Record a connection change (+1 on accept, -1 on close).
    #[inline]
    pub fn record_connection(&self, delta: i64) {
        self.metrics.record_connection(delta);
    }

    /// Check if the agent is connected to the control plane.
    #[inline]
    pub fn is_connected(&self) -> bool {
        self.client.is_connected()
    }

    /// Get the current config hash (for delta sync).
    pub fn config_hash(&self) -> String {
        self.rule_cache.config_hash()
    }

    /// Graceful shutdown — signals all background tasks to stop.
    pub async fn shutdown(&self) {
        info!("Shutting down PingWAF agent...");
        self.client.shutdown();

        // Persist cache one final time
        if let Err(e) = self.rule_cache.persist_to_disk() {
            error!(error = %e, "Failed to persist cache during shutdown");
        }

        // Clear global instance
        AGENT_INSTANCE.store(None);
        info!("PingWAF agent shut down complete");
    }
}

/// Start the PingWAF agent with the given configuration.
///
/// Convenience function that calls [`PingWafAgent::start`].
pub async fn start_agent(config: AgentConfig) -> anyhow::Result<Arc<PingWafAgent>> {
    PingWafAgent::start(config).await
}

/// Get the global agent instance (shorthand for [`PingWafAgent::instance`]).
pub fn agent_instance() -> Option<Arc<PingWafAgent>> {
    PingWafAgent::instance()
}
